const zh = {
  about: '关于',
  cancel: '取消',
  close: '关闭',
  confirmDeleteFolder: '确认删除清单',
  confirmDeleteTask: '确认删除任务',
  copy: '复制',
  createFolder: '新建清单',
  createTask: '新建任务',
  cut: '剪切',
  deleteTask: '删除',
  development: '开发',
  devTool: '调试控制台',
  edit: '编辑',
  hide: '隐藏',
  hideComplete: '隐藏',
  link: '链接',
  issus: '问题',
  mini: '最小化',
  notice: '注意',
  openSource: '开源主页',
  paste: '粘贴',
  projectHome: '项目主页',
  quite: '退出',
  redo: '重做',
  search: '搜索',
  setting: '偏好设置',
  showComplete: '显示',
  submit: '确认',
  taskComplete: '完成',
  taskImportance: '重要',
  taskNormal: '普通',
  taskStart: '开始',
  undo: '撤销',
  window: '窗口'
}

const en = {
  about: 'About',
  cancel: 'Cancel',
  close: 'Close',
  confirmDeleteFolder: 'Confirm delete folder',
  confirmDeleteTask: 'Confirm delete task',
  copy: 'Copy',
  createFolder: '+ Folder',
  createTask: '+ Task',
  cut: 'Cut',
  deleteTask: 'Delete',
  development: 'Development',
  devTool: 'Dev Tool',
  edit: 'Edit',
  hide: 'Hide',
  hideComplete: 'Hide',
  link: 'Link',
  issus: 'Issus',
  mini: 'Minimize',
  notice: 'Notice',
  openSource: 'Open Source Home',
  paste: 'Paste',
  projectHome: 'Project Home',
  quite: 'Quite',
  redo: 'ReDo',
  search: 'Search',
  setting: 'Preferences',
  showComplete: 'Show',
  submit: 'Submit',
  taskComplete: 'Completed',
  taskImportance: 'Importance',
  taskNormal: 'Normal',
  taskStart: 'Start',
  undo: 'UnDo',
  window: 'Window'
}

export default { zh, en }
